Feature/soft delete - Implemented soft delete user, recover.
OvidiuGi/internship-project pull request #41
Opened 2022-04-01 21:37 UTC by OvidiuGi

2022-04-01 21:47 UTC, OvidiuGi commented
First commit is the implementation of the functionality. (Soft deletes, and recover).
The second commit contains fixed fps violations. 
The second commit exists, because I wanted to make small commits, hope it is ok this way..

2022-04-04 08:14 UTC, Raresmldvn commented on config/packages/security.yaml
> +        - { path: ^/api/users, roles: PUBLIC_ACCESS }
this is not a good thing. it's ok if you have public access for register endpoint (so POST), but if you have a GET on users, it's not ok for everybody to access it

2022-04-04 08:14 UTC, Raresmldvn commented on migrations/Version20220401131204.php
> +        // this up() migration is auto-generated, please modify it to your needs
these comments can be removed

2022-04-04 08:14 UTC, Raresmldvn commented on src/Controller/UserController.php
> +     * @Route(path="/delete/{email}", methods={"DELETE"})
you should delete by id

2022-04-04 08:14 UTC, Raresmldvn commented on src/Controller/UserController.php
> +        $this->eventDispatcher->dispatch(new UserSoftDeleteEvent($user), UserSoftDeleteEvent::NAME);
you shouldn't actually create an event and process that in the event. you should delete the user here

2022-04-04 08:14 UTC, Raresmldvn commented on src/Controller/UserController.php
> +    public function softRecover(string $email): Response
it's just `recover` because you cannot recover a hard delete anyway

2022-04-04 08:14 UTC, Raresmldvn commented on src/Controller/UserController.php
> +     * @Route(path="/recover/{email}", methods={"GET"})
I don't really like the `GET` method here because you are doing something, not getting something. I'd prefer a `POST` with email in body

2022-04-04 08:14 UTC, Raresmldvn commented on src/Controller/UserController.php
> +        $recoveredUser = $this->userRepository->findOneBy(['email' => $email]);
if you want to have the best naming here that indicates the state of the user, please go for `userToBeRecovered`

2022-04-04 08:14 UTC, Raresmldvn commented on src/Controller/UserController.php
> +     * @Route(path="/show", methods={"GET"})
path here is weird. you can just stick to `/api/users` for this to be more RESTful. Also, an endpoint which lists all users with no pagination is not a great idea. you might have at some point thousands of users

2022-04-04 08:14 UTC, Raresmldvn commented on src/Entity/User.php
> +    public function setDeletedAt(?\DateTime $deletedAt): void
please make this setter fluent too (returns self), if you have all the other setters fluent

2022-04-04 08:14 UTC, Raresmldvn commented on src/EventSubscriber/UserSoftDeleteSubscriber.php
> +    public function checkIfTrainer(UserSoftDeleteEvent $event): void
this is the only method that should actually be in a listener. also, search for `Gedmo\SoftDeleteable\SoftDeleteableListener` class and see the events that are dispatched there. You don't really need your own events

2022-04-04 08:14 UTC, Raresmldvn commented on src/Repository/ProgrammeRepository.php
> +    public function removeTrainerById(int $id): void
try to find a more specific name here, something like `removeTrainersWithIdFromProgrammes`

2022-04-07 17:52 UTC, Raresmldvn commented on src/EventSubscriber/UserSoftDeleteSubscriber.php
> +        if (in_array('ROLE_TRAINER', $user->getRoles())) {
better to early return. `if (!in_array('ROLE_TRAINER', $user->getRoles(), true)) { return; }` and do the rest below. also, always provide the third parameter as true for `in_array` for type safety

2022-04-07 17:52 UTC, Raresmldvn requested changes
after you fix the last comment, please merge

2022-04-07 18:35 UTC, merged