Enhanced logging
OvidiuGi/internship-project pull request #47
Opened 2022-04-03 19:06 UTC by OvidiuGi

2022-04-08 08:01 UTC, live-happy-code-hard commented
I've found a series of logs missing a context that would make them helpful when you really want to see what happened there. Please consider adding useful info in the logs context. Also make sure to put the variable info in the context and not appended to the log message. That practice helps you filter logs later based on the message, which would be complicated if you combine the log message from parts.

2022-04-20 08:58 UTC, live-happy-code-hard commented on src/Command/ProgrammeImportFromCSVCommand.php
> +                    'path' => json_encode($e->getPathToFile()),
Why did you json_encode the path? WHat was the purpose?

2022-04-20 08:58 UTC, live-happy-code-hard commented on src/Command/ProgrammeImportFromAPICommand.php
> +            $numberImported . ' / ' . count($data) . ' programmes imported!',
Message should be a static text and clearly state the failure.

2022-04-20 08:59 UTC, live-happy-code-hard commented on src/Command/CreateBuildingCommand.php
> +            'Successfully created building: ',
The colon at the end of the message has no sense, the log will be processed and the context most probably wont be just printed after the message.

2022-04-20 09:00 UTC, live-happy-code-hard commented on src/Command/CreateAccountCommand.php
> +            'Successfully created account by command: ',
The colon at the end of the message is not needed

2022-04-21 08:08 UTC, calinpristavu requested changes

2022-04-21 08:08 UTC, calinpristavu commented on src/Controller/ForgotMyPasswordController.php
> +            if (date_diff(new \DateTime('now'), $user->getForgotPasswordTokenTime())->i > 60) {
there are methods on the `\DateTime` class to perform diffs.

don't ever use `\date_*` functions, but instead use their OOP alternatives implemented on the `\DateTime` class

2022-04-21 08:08 UTC, calinpristavu commented on src/Controller/ForgotMyPasswordController.php
> +            $this->logger->info('Password changed for ' . $user->email);
why not set the user email in the context?

2022-04-21 09:54 UTC, merged